import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="px-8">
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className="flex justify-center items-center w-screen h-screen">

          <h1 className="font-bebasNeue text-5xl text-ombreNaturelle31 font-bold hover:underline">
            Hello <span className="text-vert59">Quiz App!</span>
          </h1>

        </div>

      </main>

      <footer>
        <div className="flex flex-col flex-1 justify-center items-center py-8 border-t border-vert59/25">
          <div className="border border-vert59/50 rounded p-2 mb-2">
            <Image src="/favicon.png" alt="Trash Can Doodle" width={40} height={40} />
          </div>
          <p className="font-abel text-orangeVif">Scott McDonald 2021</p>
        </div>
      </footer>
    </div>
  )
}
